[workspace]
resolver = "2"
members = ["program"]

[workspace.metadata.cli]
solana = "2.3.13"

# Specify Rust toolchains for rustfmt, clippy, and build.
# Any unprovided toolchains default to stable.
[workspace.metadata.toolchains]
format = "1.90.0"
lint = "1.90.0"
